<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>aml</string>
	</array>
	<key>name</key>
	<string>Abstract Markup Language</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s{0,}?%!--</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.source.aml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--%$</string>
			<key>name</key>
			<string>comment.source.aml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s{1,})?(::)([\w|\-]+\.)?([\w|-]+)\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>method_with_attributes.source.aml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:([\w]+?)\s?=>\s?</string>
					<key>name</key>
					<string>string.source.aml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s{1,})?(::)([\w|\-]+\.)?([\w|-]+)$</string>
			<key>name</key>
			<string>method_without_attributes.source.aml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s{1,})?(?&lt;!%)%(\/{0,2})?([\w|\-]+)((\#[\w|\-]+)?((\.[\w|\-]+)?{1,})?(\#[\w|\-]+)?)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.source.aml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.source.aml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.source.aml</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.source.aml</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>string.source.aml</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>tag_with_attributes.source.aml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>{</string>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>}</string>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:([\w]+?)\s?=>\s?</string>
					<key>name</key>
					<string>string.source.aml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.source.aml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.source.aml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.source.aml</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.source.aml</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>string.source.aml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s{1,})?(?&lt;!%)%(\/{0,2})?([\w|\-]+)((\#[\w|\-]+)?((\.[\w|\-]+)?{1,})?(\#[\w|\-]+)?)?\s?(.+)?</string>
			<key>name</key>
			<string>tag_without_attributes.source.aml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^%%([^~][\w|\-]+)(\()?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.source.aml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)?{$</string>
			<key>name</key>
			<string>mixin_def.source.aml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:([\w]+?)\s?=>\s?</string>
					<key>name</key>
					<string>string.source.aml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s{1,})?%\((([\w|\-]+)\.)?([^~][\w|\-]+)\)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.source.aml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.language.source.aml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>mixin_with_attributes.source.aml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>{</string>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>}</string>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:([\w]+?)\s?=>\s?</string>
					<key>name</key>
					<string>string.source.aml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.source.aml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.language.source.aml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s{1,})?%\((([\w|\-]+)\.)?([^~][\w|\-]+)\)</string>
			<key>name</key>
			<string>mixin_without_attributes.source.aml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s{1,})?%\((\~)(([\w|\-]+)\.)?([\w|\-]+)\)\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}[^\{]?$</string>
			<key>name</key>
			<string>partial_with_attributes.source.aml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:([\w]+?)\s?=>\s?</string>
					<key>name</key>
					<string>string.source.aml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.source.aml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s{1,})?%\((\~)(([\w|\-]+)\.)?([\w|\-]+)\)$</string>
			<key>name</key>
			<string>partial_without_attributes.source.aml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.aml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.aml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.aml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.source.aml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s{1,})?(\@)(([\w|\-]+)\.)?([\w|\-]+)\s?(\=)\s?(.+)?$</string>
			<key>name</key>
			<string>variable_set.source.aml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.aml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\@\((([\w|\-]+)\.)?([\w|\-]+)\)</string>
			<key>name</key>
			<string>variable_get.source.aml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.aml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>@\(\:([\w|\-]+)\)</string>
			<key>name</key>
			<string>attribute.source.aml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s{1,})?(\-)\s?(\b(if|loop|end))\s?(.+)?$</string>
			<key>name</key>
			<string>logic_tag.source.aml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s{1,})?(\#[\w|\-]+)?((\.[\w|\-]+){1,})?(\#[\w|\-]+)?(\/{1,})?</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.source.aml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.source.aml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.source.aml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.source.aml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>tag_shorthand_with_attributes.source.aml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>{</string>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>}</string>
					<key>name</key>
					<string>variable.parameter.source.aml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:([\w]+?)\s?=>\s?</string>
					<key>name</key>
					<string>string.source.aml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.source.aml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.source.aml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.source.aml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.source.aml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s{1,})?(\#[\w|\-]+)?((\.[\w|\-]+){1,})?(\#[\w|\-]+)?(\/{1,})?(.+)?$</string>
			<key>name</key>
			<string>tag_shorthand_without_attributes.source.aml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.aml</string>
	<key>uuid</key>
	<string>e163a328-19c1-4594-92b2-5ced9021a2e5</string>
</dict>
</plist>
